# Generated by Django 4.2 on 2023-05-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_event', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_event', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('required_volunteers', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_setup.activity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_setup.event')),
            ],
            options={
                'verbose_name_plural': 'Event Activities',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desired_activities', models.ManyToManyField(to='database_setup.activity')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_setup.eventactivity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_setup.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='eventactivity',
            name='volunteers',
            field=models.ManyToManyField(blank=True, through='database_setup.VolunteerShift', to='database_setup.volunteer'),
        ),
        migrations.AddField(
            model_name='event',
            name='activities',
            field=models.ManyToManyField(through='database_setup.EventActivity', to='database_setup.activity'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_setup.volunteer')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
    ]
