# Generated by Django 4.2 on 2023-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='duration_in_chicago',
            field=models.CharField(default='< 1 month', max_length=15),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='year_in_school',
            field=models.CharField(default='M3', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='volunteershift',
            unique_together={('volunteer', 'event_activity', 'start_time', 'end_time')},
        ),
    ]
