# Generated by Django 4.2 on 2023-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_setup', '0003_alter_volunteershift_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reporting_instructions',
            field=models.TextField(default=''),
        ),
    ]
