# Generated by Django 4.2 on 2023-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_setup', '0004_event_reporting_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteershift',
            name='confirmed',
            field=models.CharField(default='No'),
        ),
    ]
